services:
  cutter:
    build: .
    container_name: cutter
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./server/db.sqlite3:/app/db.sqlite3
      - ./exports:/app/exports