services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: stroptimise-server:local
    container_name: stroptimise_server
    ports:
      - "9050:9050"
    env_file:
      - ${STROPTIMISE_ENV_FILE:-./enviroments/.env.local}
    volumes:
      - ${STROPTIMISE_DB:-./server/db.sqlite3}:/app/db.sqlite3
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: stroptimise-frontend:local
    container_name: stroptimise_frontend
    env_file:
      - ${STROPTIMISE_ENV_FILE:-./enviroments/.env.local}
    ports:
      # Map host FRONTEND_PORT to the container FRONTEND_PORT (fall back to 9060)
      - "${FRONTEND_PORT:-9060}:${FRONTEND_PORT:-9060}"
    depends_on:
      - server
    restart: unless-stopped
