services:
  server:
    build: .
    container_name: stroptimise_server
    restart: unless-stopped
    # Load environment variables from a configurable env file (defaults to ./ .env).
    env_file:
      - ${STROPTIMISE_ENV_FILE:-.env}

    ports:
      - "9050:9050"
    volumes:
      # Use host DB file if provided, otherwise fall back to a local file in the repo
      - ${STROPTIMISE_DB}:/app/db.sqlite3
      - ${STROPTIMISE_EXPORTS}:/app/exports

  frontend:
    image: nginx:stable-alpine
    container_name: stroptimise_frontend
    restart: unless-stopped
    ports:
      - "9060:9060"
    volumes:
      # Serve pre-built static files from host path (recommended on unRAID)
      - ${STROPTIMISE_FRONTEND_BUILD}:/usr/share/nginx/html
      # Mount a custom nginx config (optional) to add /api proxying
      - ${STROPTIMISE_NGINX_CONF}:/etc/nginx/conf.d/default.conf

# Notes:
# - API available on host port 9050 -> FastAPI (uvicorn)
# - Frontend static site served from host port 9060 by nginx
# - On unRAID set environment variables (see .env) or edit service volume mappings in the UI
