name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Optional: Set up Docker Buildx for advanced features and caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Optional: Cache Docker layers for faster builds
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build the Docker image
        run: docker buildx build . --file Dockerfile --tag jclass/stroptimise:${{ github.sha }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag image
        run: docker tag jclass/stroptimise:${{ github.sha }} yourdockerhubusername/your-repo:${{ github.sha }}

      - name: Push image
        run: docker push jclass/stroptimise:${{ github.sha }}
