name: Docker Image CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            # Optional: Set up Docker Buildx for advanced features and caching
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # Optional: Cache Docker layers for faster builds
            - name: Cache Docker layers
              uses: actions/cache@v4
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-

            - name: Verify Docker Hub secrets
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              run: |
                  if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ]; then
                      echo "Required Docker Hub secrets DOCKER_USERNAME or DOCKER_PASSWORD are missing." >&2
                      exit 1
                  fi

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: docker.io
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push server image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: server/Dockerfile
                  push: true
                  tags: jclass/stroptimise-server:${{ github.sha }},jclass/stroptimise-server:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Build and push frontend image
              uses: docker/build-push-action@v5
              with:
                  context: ./frontend
                  file: Dockerfile
                  push: true
                  tags: jclass/stroptimise-frontend:${{ github.sha }},jclass/stroptimise-frontend:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
