name: CI — develop tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  backend-tests:
    name: Backend tests (Python)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('server/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r server/requirements.txt -r server/requirements-dev.txt

      - name: Run backend tests
        working-directory: server
        run: |
          pytest -q

      - name: Upload pytest cache (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-cache
          path: server/.pytest_cache

  frontend-tests:
    name: Frontend tests (optional)
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Run frontend tests 
        run: |
          cd frontend
          npm test
